# Generated by Django 3.1.7 on 2021-03-15 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('category_slug', models.SlugField(max_length=100, unique=True, verbose_name='Слаг категории')),
                ('res1', models.CharField(blank=True, max_length=5, null=True)),
                ('res2', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='Название продукта')),
                ('product_slug', models.SlugField(max_length=100, unique=True)),
                ('product_image', models.ImageField(upload_to='products/%Y/%m')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('product_description', models.TextField(blank=True, max_length=10000, null=True)),
                ('product_available', models.BooleanField(default=False)),
                ('product_date', models.DateField(auto_now=True)),
                ('res1', models.CharField(blank=True, max_length=5, null=True)),
                ('res2', models.CharField(blank=True, max_length=5, null=True)),
                ('res3', models.CharField(blank=True, max_length=5, null=True)),
                ('res4', models.CharField(blank=True, max_length=5, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop_app.categoryproductmodel', verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='CartProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('res1', models.CharField(blank=True, max_length=5, null=True)),
                ('res2', models.CharField(blank=True, max_length=5, null=True)),
                ('res3', models.CharField(blank=True, max_length=5, null=True)),
                ('res4', models.CharField(blank=True, max_length=5, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_app.productmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
